# Generated by Django 3.2.25 on 2024-06-30 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0002_auto_20240630_2019'),
    ]

    operations = [
        migrations.AddField(
            model_name='tea',
            name='amount_in_gram',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tea',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='tea',
            name='image_url',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='tea',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=6),
            preserve_default=False,
        ),
    ]
