# Generated by Django 3.2.25 on 2024-06-30 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0003_auto_20240630_2030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tea',
            name='image',
        ),
        migrations.RemoveField(
            model_name='tea',
            name='image_url',
        ),
    ]
