# Generated by Django 3.2.25 on 2024-07-03 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0004_auto_20240630_2036'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tea',
        ),
    ]
