# Generated by Django 3.2.25 on 2024-06-30 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bag', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bag',
        ),
    ]
