# Generated by Django 3.2.25 on 2024-07-07 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bag', '0003_bagitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BagItem',
        ),
    ]
