# Generated by Django 3.2.25 on 2024-07-12 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bag', '0005_bagitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BagItem',
        ),
    ]
