# Generated by Django 3.2.25 on 2024-07-06 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testimonials', '0005_auto_20240627_2005'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testimonial',
            options={'ordering': ['-created_at']},
        ),
    ]
