# Generated by Django 3.2.25 on 2024-05-22 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_category_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='amount_in_gram',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
